# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: .distro/python-scikit-build.spec

files_to_sync:
  - src: .distro/python-scikit-build.spec
    dest: python-scikit-build.spec
  - .packit.yaml
  - src: .distro/python-scikit-build.rpmlintrc
    dest: python-scikit-build.rpmlintrc
  # tmt setup
  - src: .distro/.fmf/
    dest: .fmf/
  - src: .distro/plans/
    dest: plans/
    filters:
      - "- .distro/plans/main.fmf.dist-git"
      - "- .distro/plans/rpmlint.fmf"
  - src: .distro/plans/main.fmf.dist-git
    dest: plans/main.fmf
upstream_package_name: scikit-build
downstream_package_name: python-scikit-build
update_release: false

jobs:
  - job: copr_build
    trigger: pull_request
    owner: "@scikit-build"
    project: scikit-build
    update_release: true
    release_suffix: "{PACKIT_RPMSPEC_RELEASE}"
    targets:
      - fedora-development
  - job: tests
    trigger: pull_request
    targets:
      - fedora-development
    fmf_path: .distro
  - job: copr_build
    trigger: commit
    branch: main
    owner: "@scikit-build"
    project: nightly
    targets:
      - fedora-development-x86_64
      - fedora-latest-x86_64
      - fedora-development-aarch64
      - fedora-latest-aarch64
  - job: tests
    trigger: commit
    branch: main
    targets:
      - fedora-development
      - fedora-latest
    fmf_path: .distro
  - job: copr_build
    trigger: release
    owner: "@scikit-build"
    project: release
    targets:
      - fedora-development-x86_64
      - fedora-latest-x86_64
      - fedora-development-aarch64
      - fedora-latest-aarch64
  - job: propose_downstream
    trigger: release
    dist_git_branches:
      # TODO: Switch to fedora-development and fedora-latest
      # There is an issue that the commits diverge on different PRs. In the meantime will create PRs on branched fedora
      # manually
      # https://github.com/packit/packit/issues/1724
      - fedora-rawhide
  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-all
  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched
