# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: .distro/python-scikit-build.spec

upstream_package_name: scikit-build
downstream_package_name: python-scikit-build

targets:
  # TODO: Expand as scikit-build-core catches up
  - fedora-rawhide-x86_64
  - fedora-rawhide-aarch64

_:
  # Job templates
  - &build-in-packit
    job: copr_build
  - &build-in-scikit-build
    <<: *build-in-packit
    owner: "@scikit-build"
  - &tests
    job: tests
    fmf_path: .distro

jobs:
  - <<: *build-in-scikit-build
    trigger: release
    project: release
  - <<: *tests
    trigger: release
  - <<: *build-in-scikit-build
    trigger: commit
    branch: main
    project: nightly
  - <<: *tests
    trigger: commit
    branch: main
  - <<: *build-in-packit
    trigger: pull_request
  - <<: *tests
    trigger: pull_request
